### ISSUE TITLE
Imported touchstone file seems to lack shape?

### ISSUE THREAD

**Issue by eeTec** [scikit-rf/scikit-rf#295]
I'm trying to convert a s2p s Network to a Z Network.
Unfortunatly some functions seem to cause an error, others do not, however I do not see why this could happen. 

`
import skrf as rf

#SSeries = rf.Network(file=('unknownInductor_Series.s2p'))
SSeries = rf.Network(f = [1,2,3], s= [-1, 1j, 0], z0=50)

rf.plotting.plot_it_all(SSeries) #Works (???)

Z = rf.s2z(SSeries) #Does not work
rf.plotting.plot_smith(S) #Does not work
`

Error:
`
runfile('C:/Users/justRandom/Desktop/skrfTest.py', wdir='C:/Users/justRandom/Desktop')
C:\Users\justRandom\Anaconda3\lib\site-packages\skrf\mathFunctions.py:163: RuntimeWarning: divide by zero encountered in log10
  out = 20 * npy.log10(input)
Traceback (most recent call last):

  File "<ipython-input-64-7d22695c77b8>", line 1, in <module>
    runfile('C:/Users/justRandom/Desktop/skrfTest.py', wdir='C:/Users/justRandom/Desktop')

  File "C:\Users\justRandom\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\justRandom\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/justRandom/Desktop/skrfTest.py", line 20, in <module>
    Z = rf.s2z(SSeries)

  File "C:\Users\justRandom\Anaconda3\lib\site-packages\skrf\network.py", line 3816, in s2z
    nfreqs, nports, nports = s.shape

AttributeError: 'Network' object has no attribute 'shape'
`

The s2p file is attached. Please help I'm pulling my hair out on this one. Thanks :)
[network.zip](https://github.com/scikit-rf/scikit-rf/files/3646915/network.zip)

**Comment by eeTec** [comment]
Ups, my bad, correct would be to use Z = rf.s2z(SSeries**.s**)
